### ISSUE TITLE
Highlight assignments within exercise description

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#205]
In exercises where some theory is given, it's a bit hard to find what you actually have to do. 

We could use

> markdown quotes

to do that, and format them so they are visible.

**Comment by faloi** [comment]
If you quote something now, this is the result:

![image](https://cloud.githubusercontent.com/assets/1585835/8142304/901cf40e-114e-11e5-9dfd-96dfc01ab56b.png)

It's too big for me, but it could work for now.

**Comment by faloi** [comment]
And with a little CSS work:

![screenshot from 2015-06-12 22 17 46](https://cloud.githubusercontent.com/assets/1585835/8142373/4f5c509c-1151-11e5-864f-5afcce7c90d8.png)

```css
.alert-warning-modified {
    background-color: #FFE4B8;
    border-color: #f39c12;
    color: #413838;
    font-size: 15px;
}
```
